version: "3.8"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres_data:
